import { db } from "../../config/database";
import {
  clientTable,
  transaction,
  enquiry_table,
  quote,
  booking,
  type NeonClient,
  type InsertClientTable,
} from "@shared/schema";
import { eq, desc, asc, sql, count, or, and, ilike, inArray, getTableColumns, type SQL } from "drizzle-orm";
import type { Scope } from "../../utils/scope";
import { phoneDigitsCondition } from "../../utils/phone-search";
import { clientNameCondition } from "../../utils/client-name-search";

// Import rows never carry identity or tenant columns — id is generated by the
// database and orgId/branchId/createdBy are assigned server-side from the
// caller's scope, so an import can never write into another tenant's data.
export type NeonClientImport = Omit<InsertClientTable, "id" | "orgId" | "branchId" | "createdBy">;

const BATCH_SIZE = 100;

function buildClientScopeConds(scope?: Scope): SQL[] {
  const conds: SQL[] = [];
  if (!scope || scope.orgRole === "platform_admin") return conds;
  conds.push(eq(clientTable.orgId, scope.orgId));
  if (scope.orgRole === "branch_manager" && scope.branchId) {
    conds.push(eq(clientTable.branchId, scope.branchId));
  }
  if (scope.orgRole === "homeworker" && scope.userId) {
    conds.push(eq(clientTable.createdBy, scope.userId));
  }
  return conds;
}

// Merged (soft-archived) duplicates are hidden from list/search views.
const activeOnly = eq(clientTable.status, "active");

// Name matching is shared with the global header search (see clientNameCondition)
// — previously findPaginated OR-ed each word across firstName and surename
// independently, so "John Smith" returned every John AND every Smith and the
// actual John Smith could fall past the page limit.
function buildClientSearchClause(search?: string): SQL | undefined {
  if (!search) return undefined;
  const phoneDigits = phoneDigitsCondition(clientTable.phoneNumber, search);
  const nameCondition = clientNameCondition(clientTable.firstName, clientTable.surename, search);
  return or(
    ...(nameCondition ? [nameCondition] : []),
    ilike(clientTable.email, `%${search}%`),
    ilike(clientTable.phoneNumber, `%${search}%`),
    ...(phoneDigits ? [phoneDigits] : []),
    ilike(clientTable.city, `%${search}%`),
    ilike(clientTable.country, `%${search}%`),
  );
}

// Duplicate-detection key: the LAST 9 DIGITS of the stored phone number.
// Grouping on the whole digit string would file "07968215588" and
// "+447968215588" as different people — the single most common way one client
// ends up stored twice. Nine digits stays specific (a full UK subscriber
// number) while absorbing the 0 / +44 prefix difference. Numbers carrying
// fewer than 9 digits are excluded outright: a short key would collide across
// unrelated clients and report duplicates that aren't.
const PHONE_KEY_LENGTH = 9;
const phoneKeyLength = sql.raw(String(PHONE_KEY_LENGTH));
const phoneDigitsExpr = sql`regexp_replace(COALESCE(${clientTable.phoneNumber}, ''), '[^0-9]', '', 'g')`;
const phoneKeyExpr = sql`right(${phoneDigitsExpr}, ${phoneKeyLength})`;
const phoneKeyUsable = sql`length(${phoneDigitsExpr}) >= ${phoneKeyLength}`;

export type DuplicatePhoneGroupRow = {
  phoneKey: string;
  clientCount: number;
  samplePhone: string;
  clientNames: string;
};

export type ClientDealCounts = {
  // Nullable because `transaction.client_id` is — the inArray filter means it
  // never actually comes back null here.
  clientId: string | null;
  enquiryCount: number;
  quoteCount: number;
  bookingCount: number;
  lastActivityAt: Date | null;
};

export const neonClientRepository = {
  async findById(id: string, scope?: Scope): Promise<NeonClient | undefined> {
    const conds: SQL[] = [eq(clientTable.id, id), ...buildClientScopeConds(scope)];
    const [result] = await db.select().from(clientTable).where(and(...conds)).limit(1);
    return result;
  },

  /** Lightweight VIP-fields lookup used by enrollment. */
  async findVipEnrolledAt(id: string): Promise<{ vipEnrolledAt: Date | null } | undefined> {
    const [row] = await db
      .select({ vipEnrolledAt: clientTable.vipEnrolledAt })
      .from(clientTable)
      .where(eq(clientTable.id, id))
      .limit(1);
    return row;
  },

  /** Initialise VIP fields on a client (no-op if already enrolled). */
  async enrollVip(id: string): Promise<void> {
    await db
      .update(clientTable)
      .set({ vipTier: 'standard', vipEnrolledAt: new Date(), totalReferrals: 0 })
      .where(eq(clientTable.id, id));
  },

  async setVipTotalsAndTier(id: string, totalReferrals: number, vipTier: 'standard' | 'gold' | 'elite'): Promise<void> {
    await db
      .update(clientTable)
      .set({ totalReferrals, vipTier })
      .where(eq(clientTable.id, id));
  },

  async findPortalPin(id: string): Promise<{ portalPin: string | null } | undefined> {
    const [row] = await db
      .select({ portalPin: clientTable.portalPin })
      .from(clientTable)
      .where(eq(clientTable.id, id))
      .limit(1);
    return row;
  },

  async setPortalPin(id: string, hash: string | null, opts?: { mustChange?: boolean }): Promise<void> {
    // Default the flag to false: staff-set / client-chosen PINs are final, only
    // a system-seeded default (mustChange: true) requires a forced change.
    await db
      .update(clientTable)
      .set({ portalPin: hash, mustChangePin: opts?.mustChange ?? false })
      .where(eq(clientTable.id, id));
  },

  async findAll(scope?: Scope): Promise<NeonClient[]> {
    const conds = [...buildClientScopeConds(scope), activeOnly];
    return await db.select().from(clientTable)
      .where(and(...conds))
      .orderBy(desc(clientTable.createdAt));
  },

  async findPaginated(page: number, limit: number, search?: string, scope?: Scope): Promise<{ clients: NeonClient[]; total: number }> {
    const offset = (page - 1) * limit;

    const searchClause = buildClientSearchClause(search);

    const scopeConds = buildClientScopeConds(scope);
    const allConds: SQL[] = [...scopeConds, activeOnly];
    if (searchClause) allConds.push(searchClause);
    const whereClause = and(...allConds);

    const latestTransaction = db
      .select({
        clientId: transaction.client_id,
        latestActivity: sql<string>`MAX(${transaction.created_at})`.as("latest_activity"),
      })
      .from(transaction)
      .groupBy(transaction.client_id)
      .as("latest_tx");

    const clientColumns = getTableColumns(clientTable);

    const [clients, totalResult] = await Promise.all([
      db.select({ ...clientColumns })
        .from(clientTable)
        .leftJoin(latestTransaction, eq(clientTable.id, latestTransaction.clientId))
        .where(whereClause)
        .orderBy(
          sql`${latestTransaction.latestActivity} IS NULL ASC`,
          desc(sql`${latestTransaction.latestActivity}`),
          desc(clientTable.createdAt)
        )
        .limit(limit)
        .offset(offset),
      db.select({ total: count() }).from(clientTable)
        .where(whereClause),
    ]);

    return { clients, total: totalResult[0]?.total ?? 0 };
  },

  // One row per phone number that more than one active client shares. Only the
  // group key and a summary come back — the clients themselves are fetched
  // per-group by findByPhoneKey when the user opens one, so the list page stays
  // cheap however many duplicates exist.
  //
  // Ordered SMALLEST group first, deliberately. A pair of records on one number
  // is nearly always one person entered twice; a number carrying dozens of
  // unrelated names is a shop/placeholder number (live data has 56 different
  // clients on the office landline) where merging would be destructive. Putting
  // the big groups last keeps the genuinely mergeable cases on page one.
  async findDuplicatePhoneGroups(
    page: number,
    limit: number,
    search: string | undefined,
    scope?: Scope,
  ): Promise<{ groups: DuplicatePhoneGroupRow[]; total: number }> {
    const offset = (page - 1) * limit;
    const whereClause = and(...buildClientScopeConds(scope), activeOnly, phoneKeyUsable);

    // The search filter is applied in HAVING via bool_or, NOT in WHERE:
    // filtering rows before the GROUP BY would drop a group's non-matching
    // members, shrinking its count — and a two-client group where only one
    // member matched would fall below `count(*) > 1` and vanish entirely.
    // bool_or keeps every group whole and simply keeps the ones where at least
    // one member matches.
    const searchClause = buildClientSearchClause(search);
    const duplicatesOnly = sql`count(*) > 1`;
    const havingClause = searchClause
      ? and(duplicatesOnly, sql`bool_or(${searchClause})`)
      : duplicatesOnly;

    const groupsQuery = db
      .select({
        phoneKey: sql<string>`${phoneKeyExpr}`.as("phone_key"),
        clientCount: sql<number>`count(*)::int`.as("client_count"),
        // A representative of the raw stored formats, for display — the key
        // itself is digits-only and unreadable as a phone number.
        samplePhone: sql<string>`min(${clientTable.phoneNumber})`.as("sample_phone"),
        clientNames: sql<string>`string_agg(trim(concat(${clientTable.firstName}, ' ', ${clientTable.surename})), ', ')`.as("client_names"),
      })
      .from(clientTable)
      .where(whereClause)
      .groupBy(phoneKeyExpr)
      .having(havingClause);

    const totalSubquery = db
      .select({ phoneKey: sql<string>`${phoneKeyExpr}`.as("phone_key") })
      .from(clientTable)
      .where(whereClause)
      .groupBy(phoneKeyExpr)
      .having(havingClause)
      .as("duplicate_groups");

    const [groups, totalResult] = await Promise.all([
      groupsQuery
        .orderBy(asc(sql`count(*)`), sql`${phoneKeyExpr}`)
        .limit(limit)
        .offset(offset),
      db.select({ total: count() }).from(totalSubquery),
    ]);

    return { groups, total: totalResult[0]?.total ?? 0 };
  },

  // Every active client sharing one duplicate-phone key, oldest first (the
  // original record is usually the one worth keeping, so it leads).
  async findByPhoneKey(phoneKey: string, scope?: Scope): Promise<NeonClient[]> {
    const conds: SQL[] = [
      ...buildClientScopeConds(scope),
      activeOnly,
      phoneKeyUsable,
      sql`${phoneKeyExpr} = ${phoneKey}`,
    ];
    return db.select().from(clientTable).where(and(...conds)).orderBy(asc(clientTable.createdAt));
  },

  // Enquiry / quote / booking volume + last activity per client. All three hang
  // off `transaction.client_id`, so one grouped query covers them — this is what
  // tells the user which of the duplicates is the real record.
  //
  // COUNT(DISTINCT ...) is load-bearing, not defensive: a transaction can carry
  // several quotes, so joining all three tables at once fans out into a cross
  // product and a plain count(*) would multiply the enquiry and booking totals
  // by the number of quotes.
  async countDealsByClientIds(clientIds: string[]): Promise<ClientDealCounts[]> {
    if (clientIds.length === 0) return [];
    return db
      .select({
        clientId: transaction.client_id,
        enquiryCount: sql<number>`count(distinct ${enquiry_table.id})::int`,
        quoteCount: sql<number>`count(distinct ${quote.id})::int`,
        bookingCount: sql<number>`count(distinct ${booking.id})::int`,
        lastActivityAt: sql<Date | null>`max(${transaction.created_at})`,
      })
      .from(transaction)
      .leftJoin(enquiry_table, eq(enquiry_table.transaction_id, transaction.id))
      .leftJoin(quote, eq(quote.transaction_id, transaction.id))
      .leftJoin(booking, eq(booking.transaction_id, transaction.id))
      .where(inArray(transaction.client_id, clientIds))
      .groupBy(transaction.client_id);
  },

  // Finds active clients whose email or phone matches the given values — used to
  // suggest a client to link a SendSeven contact to. Phone comparison is done on
  // digits only so "+44 175…" matches "0175…" etc. Returns a small candidate set.
  async findMatches(opts: { phone?: string | null; email?: string | null }, scope?: Scope): Promise<NeonClient[]> {
    const matchers: SQL[] = [];

    const email = opts.email?.trim();
    if (email) matchers.push(ilike(clientTable.email, email));

    const phoneDigits = (opts.phone ?? "").replace(/\D/g, "");
    if (phoneDigits.length >= 7) {
      const tail = phoneDigits.slice(-8);
      matchers.push(sql`regexp_replace(${clientTable.phoneNumber}, '[^0-9]', '', 'g') LIKE ${`%${tail}`}`);
    }

    if (matchers.length === 0) return [];

    const conds: SQL[] = [...buildClientScopeConds(scope), activeOnly, or(...matchers) as SQL];
    return db.select().from(clientTable).where(and(...conds)).orderBy(desc(clientTable.createdAt)).limit(5);
  },

  // Weaker fallback used only when phone/email found nothing: clients whose first
  // and last name both equal the inbox contact's, case-insensitively.
  //
  // Deliberately an exact (not fuzzy) name comparison — Postgres trigram search
  // would need the pg_trgm extension, which this database doesn't install, and a
  // loose match on a common name returns a wall of wrong people. Callers must
  // present these as "same name, check before linking", never as a confident match.
  //
  // Uses the FIRST and LAST tokens of the display name so a middle name
  // ("Sarah Jane Jenkins") still matches a stored "Sarah" + "Jenkins".
  async findNameMatches(name: string | null | undefined, scope?: Scope): Promise<NeonClient[]> {
    const parts = (name ?? "").trim().split(/\s+/).filter(Boolean);
    // A single token ("Joe", or an Instagram handle) is far too broad to suggest on.
    if (parts.length < 2) return [];

    const first = parts[0];
    const last = parts[parts.length - 1];

    const conds: SQL[] = [
      ...buildClientScopeConds(scope),
      activeOnly,
      sql`lower(trim(${clientTable.firstName})) = lower(${first})`,
      sql`lower(trim(${clientTable.surename})) = lower(${last})`,
    ];
    // Capped low: a long list of same-name maybes is worse than none.
    return db.select().from(clientTable).where(and(...conds)).orderBy(desc(clientTable.createdAt)).limit(3);
  },

  async create(client: InsertClientTable, scope?: Scope): Promise<NeonClient> {
    const values: InsertClientTable = scope
      ? ({
          ...client,
          orgId: (client as any).orgId ?? scope.orgId ?? null,
          branchId: (client as any).branchId ?? scope.branchId ?? null,
          createdBy: (client as any).createdBy ?? scope.userId ?? null,
        } as InsertClientTable)
      : client;
    const [result] = await db.insert(clientTable).values(values).returning();
    return result;
  },

  async update(id: string, client: Partial<InsertClientTable>, scope?: Scope): Promise<NeonClient | undefined> {
    const conds: SQL[] = [eq(clientTable.id, id), ...buildClientScopeConds(scope)];
    const [result] = await db.update(clientTable).set(client).where(and(...conds)).returning();
    return result;
  },

  async remove(id: string, scope?: Scope): Promise<boolean> {
    const conds: SQL[] = [eq(clientTable.id, id), ...buildClientScopeConds(scope)];
    const result = await db.delete(clientTable).where(and(...conds)).returning({ id: clientTable.id });
    return result.length > 0;
  },

  async bulkInsert(clients: NeonClientImport[], scope?: Scope): Promise<{ imported: number; errors: Array<{ row: number; id: string; error: string }> }> {
    const errors: Array<{ row: number; id: string; error: string }> = [];
    let imported = 0;

    // Insert-only. Tenant ownership is forced from the caller's scope and id is
    // left unset (DB-generated), so a row can neither overwrite an existing
    // record nor be planted into another org/branch.
    const stamped = clients.map((c) => ({
      ...c,
      orgId: scope?.orgId ?? null,
      branchId: scope?.branchId ?? null,
      createdBy: scope?.userId ?? null,
    }));

    for (let batchStart = 0; batchStart < stamped.length; batchStart += BATCH_SIZE) {
      const batch = stamped.slice(batchStart, batchStart + BATCH_SIZE);
      try {
        await db.insert(clientTable).values(batch);
        imported += batch.length;
      } catch {
        for (let i = 0; i < batch.length; i++) {
          const client = batch[i]!;
          try {
            await db.insert(clientTable).values(client);
            imported++;
          } catch (rowErr: any) {
            errors.push({
              row: batchStart + i + 1,
              id: "-",
              error: rowErr.message || "Unknown error",
            });
          }
        }
      }
    }

    return { imported, errors };
  },
};
