import { db } from "../../config/database";
import { clientTable, transaction, type NeonClient, type InsertClientTable } from "@shared/schema";
import { eq, desc, sql, count, or, and, ilike, getTableColumns, type SQL } from "drizzle-orm";
import type { Scope } from "../../utils/scope";

// Import rows never carry identity or tenant columns — id is generated by the
// database and orgId/branchId/createdBy are assigned server-side from the
// caller's scope, so an import can never write into another tenant's data.
export type NeonClientImport = Omit<InsertClientTable, "id" | "orgId" | "branchId" | "createdBy">;

const BATCH_SIZE = 100;

function buildClientScopeConds(scope?: Scope): SQL[] {
  const conds: SQL[] = [];
  if (!scope || scope.orgRole === "platform_admin") return conds;
  conds.push(eq(clientTable.orgId, scope.orgId));
  if (scope.orgRole === "branch_manager" && scope.branchId) {
    conds.push(eq(clientTable.branchId, scope.branchId));
  }
  if (scope.orgRole === "homeworker" && scope.userId) {
    conds.push(eq(clientTable.createdBy, scope.userId));
  }
  return conds;
}

export const neonClientRepository = {
  async findById(id: string, scope?: Scope): Promise<NeonClient | undefined> {
    const conds: SQL[] = [eq(clientTable.id, id), ...buildClientScopeConds(scope)];
    const [result] = await db.select().from(clientTable).where(and(...conds)).limit(1);
    return result;
  },

  /** Lightweight VIP-fields lookup used by enrollment. */
  async findVipEnrolledAt(id: string): Promise<{ vipEnrolledAt: Date | null } | undefined> {
    const [row] = await db
      .select({ vipEnrolledAt: clientTable.vipEnrolledAt })
      .from(clientTable)
      .where(eq(clientTable.id, id))
      .limit(1);
    return row;
  },

  /** Initialise VIP fields on a client (no-op if already enrolled). */
  async enrollVip(id: string): Promise<void> {
    await db
      .update(clientTable)
      .set({ vipTier: 'standard', vipEnrolledAt: new Date(), totalReferrals: 0 })
      .where(eq(clientTable.id, id));
  },

  async setVipTotalsAndTier(id: string, totalReferrals: number, vipTier: 'standard' | 'gold' | 'elite'): Promise<void> {
    await db
      .update(clientTable)
      .set({ totalReferrals, vipTier })
      .where(eq(clientTable.id, id));
  },

  async findPortalPin(id: string): Promise<{ portalPin: string | null } | undefined> {
    const [row] = await db
      .select({ portalPin: clientTable.portalPin })
      .from(clientTable)
      .where(eq(clientTable.id, id))
      .limit(1);
    return row;
  },

  async setPortalPin(id: string, hash: string | null, opts?: { mustChange?: boolean }): Promise<void> {
    // Default the flag to false: staff-set / client-chosen PINs are final, only
    // a system-seeded default (mustChange: true) requires a forced change.
    await db
      .update(clientTable)
      .set({ portalPin: hash, mustChangePin: opts?.mustChange ?? false })
      .where(eq(clientTable.id, id));
  },

  async findAll(scope?: Scope): Promise<NeonClient[]> {
    const conds = buildClientScopeConds(scope);
    const query = db.select().from(clientTable);
    return conds.length > 0
      ? await query.where(and(...conds)).orderBy(desc(clientTable.createdAt))
      : await query.orderBy(desc(clientTable.createdAt));
  },

  async findPaginated(page: number, limit: number, search?: string, scope?: Scope): Promise<{ clients: NeonClient[]; total: number }> {
    const offset = (page - 1) * limit;

    const words = search ? search.trim().split(/\s+/).filter(Boolean) : [];
    const wordTerms = words.map((w) => `%${w}%`);

    const searchClause = search
      ? or(
          ...wordTerms.map((t) => ilike(clientTable.firstName, t)),
          ...wordTerms.map((t) => ilike(clientTable.surename, t)),
          ilike(clientTable.email, `%${search}%`),
          ilike(clientTable.phoneNumber, `%${search}%`),
          ilike(clientTable.city, `%${search}%`),
          ilike(clientTable.country, `%${search}%`),
          sql`concat_ws(' ', ${clientTable.firstName}, ${clientTable.surename}) ilike ${`%${search}%`}`,
        )
      : undefined;

    const scopeConds = buildClientScopeConds(scope);
    const allConds: SQL[] = [...scopeConds];
    if (searchClause) allConds.push(searchClause);
    const whereClause = allConds.length > 0 ? and(...allConds) : undefined;

    const latestTransaction = db
      .select({
        clientId: transaction.client_id,
        latestActivity: sql<string>`MAX(${transaction.created_at})`.as("latest_activity"),
      })
      .from(transaction)
      .groupBy(transaction.client_id)
      .as("latest_tx");

    const clientColumns = getTableColumns(clientTable);

    const [clients, totalResult] = await Promise.all([
      db.select({ ...clientColumns })
        .from(clientTable)
        .leftJoin(latestTransaction, eq(clientTable.id, latestTransaction.clientId))
        .where(whereClause)
        .orderBy(
          sql`${latestTransaction.latestActivity} IS NULL ASC`,
          desc(sql`${latestTransaction.latestActivity}`),
          desc(clientTable.createdAt)
        )
        .limit(limit)
        .offset(offset),
      db.select({ total: count() }).from(clientTable)
        .where(whereClause),
    ]);

    return { clients, total: totalResult[0]?.total ?? 0 };
  },

  async create(client: InsertClientTable, scope?: Scope): Promise<NeonClient> {
    const values: InsertClientTable = scope
      ? ({
          ...client,
          orgId: (client as any).orgId ?? scope.orgId ?? null,
          branchId: (client as any).branchId ?? scope.branchId ?? null,
          createdBy: (client as any).createdBy ?? scope.userId ?? null,
        } as InsertClientTable)
      : client;
    const [result] = await db.insert(clientTable).values(values).returning();
    return result;
  },

  async update(id: string, client: Partial<InsertClientTable>, scope?: Scope): Promise<NeonClient | undefined> {
    const conds: SQL[] = [eq(clientTable.id, id), ...buildClientScopeConds(scope)];
    const [result] = await db.update(clientTable).set(client).where(and(...conds)).returning();
    return result;
  },

  async remove(id: string, scope?: Scope): Promise<boolean> {
    const conds: SQL[] = [eq(clientTable.id, id), ...buildClientScopeConds(scope)];
    const result = await db.delete(clientTable).where(and(...conds)).returning({ id: clientTable.id });
    return result.length > 0;
  },

  async bulkInsert(clients: NeonClientImport[], scope?: Scope): Promise<{ imported: number; errors: Array<{ row: number; id: string; error: string }> }> {
    const errors: Array<{ row: number; id: string; error: string }> = [];
    let imported = 0;

    // Insert-only. Tenant ownership is forced from the caller's scope and id is
    // left unset (DB-generated), so a row can neither overwrite an existing
    // record nor be planted into another org/branch.
    const stamped = clients.map((c) => ({
      ...c,
      orgId: scope?.orgId ?? null,
      branchId: scope?.branchId ?? null,
      createdBy: scope?.userId ?? null,
    }));

    for (let batchStart = 0; batchStart < stamped.length; batchStart += BATCH_SIZE) {
      const batch = stamped.slice(batchStart, batchStart + BATCH_SIZE);
      try {
        await db.insert(clientTable).values(batch);
        imported += batch.length;
      } catch {
        for (let i = 0; i < batch.length; i++) {
          const client = batch[i]!;
          try {
            await db.insert(clientTable).values(client);
            imported++;
          } catch (rowErr: any) {
            errors.push({
              row: batchStart + i + 1,
              id: "-",
              error: rowErr.message || "Unknown error",
            });
          }
        }
      }
    }

    return { imported, errors };
  },
};
