import { Router } from "express";
import userRoutes from "./user.routes";
import clientRoutes from "./client.routes";
import transactionRoutes from "./transaction.routes";
import quoteRoutes from "./quote.routes";
import bookingRoutes from "./booking.routes";
import noteRoutes from "./note.routes";
import tourOperatorRoutes from "./tourOperator.routes";
import airportRoutes from "./airport.routes";
import ticketRoutes from "./ticket.routes";
import ticketAttachmentRoutes from "./ticketAttachment.routes";
import ticketReplyRoutes from "./ticketReply.routes";
import notificationRoutes from "./notification.routes";
import neonClientRoutes from "./neonClient.routes";
import dashboardRoutes from "./dashboard.routes";
import enquiryRoutes from "./enquiry.routes";
import favoriteRoutes from "./favorite.routes";
import adminImportRoutes from "./adminImport.routes";
import taskRoutes from "./task.routes";
import lookupRoutes from "./lookup.routes";
import jsonMapperRoutes from "./json-mapper.routes";
import tagRoutes from "./tag.routes";
import chatRoutes from "./chat.routes";

const router = Router();

router.use("/users", userRoutes);
router.use("/clients", clientRoutes);
router.use("/transactions", transactionRoutes);
router.use("/quotes", quoteRoutes);
router.use("/bookings", bookingRoutes);
router.use("/enquiries", enquiryRoutes);
router.use("/notes", noteRoutes);
router.use("/tour-operators", tourOperatorRoutes);
router.use("/airports", airportRoutes);
router.use("/tickets", ticketRoutes);
router.use("/attachments", ticketAttachmentRoutes);
router.use("/replies", ticketReplyRoutes);
router.use("/notifications", notificationRoutes);
router.use("/neon-clients", neonClientRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/favorites", favoriteRoutes);
router.use("/admin", adminImportRoutes);
router.use("/tasks", taskRoutes);
router.use("/lookup", lookupRoutes);
router.use("/json-mapper", jsonMapperRoutes);
router.use("/tags", tagRoutes);
router.use("/chat", chatRoutes);

export default router;
