import { Router } from "express";
import userRoutes from "./user.routes";
import clientRoutes from "./client.routes";
import transactionRoutes from "./transaction.routes";
import quoteRoutes from "./quote.routes";
import bookingRoutes from "./booking.routes";
import noteRoutes from "./note.routes";
import tourOperatorRoutes from "./tourOperator.routes";
import airportRoutes from "./airport.routes";
import ticketRoutes from "./ticket.routes";
import ticketAttachmentRoutes from "./ticketAttachment.routes";
import ticketReplyRoutes from "./ticketReply.routes";
import notificationRoutes from "./notification.routes";
import neonClientRoutes from "./neonClient.routes";
import dashboardRoutes from "./dashboard.routes";
import enquiryRoutes from "./enquiry.routes";
import favoriteRoutes from "./favorite.routes";
import adminImportRoutes from "./adminImport.routes";
import taskRoutes from "./task.routes";
import lookupRoutes from "./lookup.routes";
import jsonMapperRoutes from "./json-mapper.routes";
import tagRoutes from "./tag.routes";
import chatRoutes from "./chat.routes";
import socialPostRoutes from "./social-post.routes";
import settingsRoutes from "./settings.routes";
import clientFileRoutes from "./clientFile.routes";
import userProfileRoutes from "./userProfile.routes";
import emailRoutes from "./email.routes";
import facebookRoutes from "./facebook.routes";
import opportunitiesRoutes from "./opportunities.routes";
import revenueRoutes from "./revenue.routes";
import targetsRoutes from "./targets.routes";
import searchRoutes from "./search.routes";
import destinationGuruRoutes from "./destination-guru.routes";
import feedbackRoutes from "./feedback.routes";
import announcementRoutes from "./announcement.routes";
import quoteShareRoutes from "./quote-share.routes";
import auditRoutes from "./audit.routes";
import hubPostRoutes from "./hubPost.routes";
import referralRoutes from "./referral.routes";
import referralPayoutRoutes from "./referralPayout.routes";
import referralWithdrawalRoutes from "./referralWithdrawal.routes";
import walletRoutes from "./wallet.routes";
import smsRoutes from "./sms.routes";
import hrRoutes from "./hr.routes";
import aiAskRoutes from "./ai-ask.routes";

const router = Router();

router.use("/users", userRoutes);
router.use("/clients", clientRoutes);
router.use("/transactions", transactionRoutes);
router.use("/quotes", quoteRoutes);
router.use("/bookings", bookingRoutes);
router.use("/enquiries", enquiryRoutes);
router.use("/notes", noteRoutes);
router.use("/tour-operators", tourOperatorRoutes);
router.use("/airports", airportRoutes);
router.use("/tickets", ticketRoutes);
router.use("/attachments", ticketAttachmentRoutes);
router.use("/replies", ticketReplyRoutes);
router.use("/notifications", notificationRoutes);
router.use("/neon-clients", neonClientRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/favorites", favoriteRoutes);
router.use("/admin", adminImportRoutes);
router.use("/tasks", taskRoutes);
router.use("/lookup", lookupRoutes);
router.use("/json-mapper", jsonMapperRoutes);
router.use("/tags", tagRoutes);
router.use("/chat", chatRoutes);
router.use("/social-posts", socialPostRoutes);
router.use("/settings", settingsRoutes);
router.use("/client-files", clientFileRoutes);
router.use("/user-profiles", userProfileRoutes);
router.use("/emails", emailRoutes);
router.use("/facebook", facebookRoutes);
router.use("/opportunities", opportunitiesRoutes);
router.use("/revenue", revenueRoutes);
router.use("/targets", targetsRoutes);
router.use("/search", searchRoutes);
router.use("/destination-guru", destinationGuruRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/announcements", announcementRoutes);
router.use("/quote-share", quoteShareRoutes);
router.use("/audit", auditRoutes);
router.use("/hub-posts", hubPostRoutes);
router.use("/referrals", referralRoutes);
router.use("/referral-payouts", referralPayoutRoutes);
router.use("/referral-withdrawals", referralWithdrawalRoutes);
router.use("/wallet", walletRoutes);
router.use("/sms", smsRoutes);
router.use("/hr", hrRoutes);
router.use("/ai", aiAskRoutes);

export default router;
