import { useMemo, useState } from "react";
import { AlertTriangle, Check, Loader2, RotateCcw } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { useApproveSupplierSpec } from "../api/use-supplier-scrapers";
import type { SupplierScraper } from "../types";

interface FieldRule {
  from?: string;
  jsonPath?: string;
  regex?: string;
  urlSegment?: number;
  transform?: string;
}

// An AI-generated spec is learned from ONE page, so its rules are routinely
// pinned to that deal's own values — a literal board basis, this hotel's name,
// one airport code. Such a rule extracts nothing on the next deal, or worse,
// stamps the first deal's value on every later one. Surfacing the rules that
// look pinned is the whole point of the review step.
function looksOverfitted(rule: FieldRule): boolean {
  const pattern = rule.regex ?? "";
  if (!pattern) return false;
  // A regex with no capture-group wildcard is matching a fixed phrase.
  const hasWildcard = /\[|\\d|\\w|\\s|\.\+|\.\*|\+|\*/.test(pattern);
  const looksLikeProse = /[A-Z][a-z]+\s+[A-Z][a-z]+/.test(pattern);
  return !hasWildcard || (looksLikeProse && !/\|/.test(pattern));
}

interface SupplierSpecReviewDialogProps {
  scraper: SupplierScraper | null;
  onOpenChange: (open: boolean) => void;
}

export function SupplierSpecReviewDialog({ scraper, onOpenChange }: SupplierSpecReviewDialogProps) {
  const approveMutation = useApproveSupplierSpec();
  const { toast } = useToast();
  const [showRaw, setShowRaw] = useState(false);

  const config = (scraper?.config ?? {}) as {
    extraction?: { fields?: Record<string, FieldRule>; constants?: Record<string, unknown> };
    specNeedsReview?: boolean;
  };
  const spec = config.extraction;
  const needsReview = config.specNeedsReview === true;

  const rules = useMemo(() => Object.entries(spec?.fields ?? {}), [spec]);
  const suspect = useMemo(() => rules.filter(([, r]) => looksOverfitted(r)).map(([k]) => k), [rules]);

  const submit = (approve: boolean) => {
    if (!scraper) return;
    approveMutation.mutate(
      { id: scraper.id, approve },
      {
        onSuccess: () => {
          toast({
            title: approve ? "Spec approved" : "Sent back for review",
            description: scraper.supplierName,
          });
          onOpenChange(false);
        },
        onError: (err: unknown) =>
          toast({
            title: "Could not update the spec",
            description: err instanceof Error ? err.message : "Please try again.",
            variant: "destructive",
          }),
      },
    );
  };

  return (
    <Dialog open={!!scraper} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-[720px]">
        <DialogHeader>
          <DialogTitle>Extraction spec — {scraper?.supplierName}</DialogTitle>
          <DialogDescription>
            These rules were generated by AI from a single captured page, and decide what every future import from
            this supplier reads. Approving marks them checked; it doesn't change how they run.
          </DialogDescription>
        </DialogHeader>

        {!spec ? (
          <p className="text-sm text-black/60">
            No spec yet — capture a deal page for this supplier and one will be generated.
          </p>
        ) : (
          <div className="space-y-4">
            <div className="flex flex-wrap items-center gap-2">
              <span
                className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
                  needsReview ? "bg-amber-500/15 text-amber-700" : "bg-emerald-500/15 text-emerald-700"
                }`}
              >
                {needsReview ? "Needs review" : "Approved"}
              </span>
              <span className="text-xs text-black/45">{rules.length} field rules</span>
            </div>

            {suspect.length > 0 && (
              <div className="flex gap-2 rounded-xl border border-amber-500/30 bg-amber-500/5 p-3">
                <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
                <div className="text-xs text-black/70">
                  <strong>Check these before approving:</strong> {suspect.join(", ")}.
                  <div className="mt-1 text-black/50">
                    Their patterns look pinned to the one deal the spec was learned from, so they may extract nothing
                    — or the wrong value — on the next deal.
                  </div>
                </div>
              </div>
            )}

            <div className="overflow-hidden rounded-xl border border-black/10">
              <div className="grid grid-cols-[150px_60px_1fr] gap-2 border-b border-black/5 bg-black/[0.02] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wider text-black/50">
                <div>Field</div>
                <div>Source</div>
                <div>Rule</div>
              </div>
              <div className="divide-y divide-black/5">
                {rules.map(([name, rule]) => (
                  <div key={name} className="grid grid-cols-[150px_60px_1fr] items-start gap-2 px-3 py-2 text-xs">
                    <div className={`font-medium ${suspect.includes(name) ? "text-amber-700" : "text-black/70"}`}>
                      {name}
                    </div>
                    <div className="text-black/45">{rule.jsonPath ? "json" : (rule.from ?? "text")}</div>
                    <div className="min-w-0 break-all font-mono text-[10px] text-black/60">
                      {rule.jsonPath ?? rule.regex ?? (rule.urlSegment != null ? `segment ${rule.urlSegment}` : "—")}
                      {rule.transform ? <span className="text-black/35"> → {rule.transform}</span> : null}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <button
              type="button"
              onClick={() => setShowRaw((v) => !v)}
              className="text-xs font-medium text-black/50 hover:text-black/70"
            >
              {showRaw ? "Hide" : "Show"} raw JSON
            </button>
            {showRaw && (
              <textarea
                readOnly
                value={JSON.stringify(spec, null, 2)}
                onFocus={(e) => e.currentTarget.select()}
                className="h-56 w-full rounded-xl border border-black/10 bg-white/70 p-2 font-mono text-[10px] text-black/60"
              />
            )}
          </div>
        )}

        <DialogFooter className="gap-2">
          {spec && !needsReview && (
            <button
              type="button"
              onClick={() => submit(false)}
              disabled={approveMutation.isPending}
              className="flex items-center gap-1.5 rounded-xl border border-black/10 bg-white/70 px-3 py-1.5 text-xs font-medium text-black/60 transition hover:bg-black/5 disabled:opacity-50"
            >
              <RotateCcw className="h-3.5 w-3.5" />
              Send back for review
            </button>
          )}
          {spec && needsReview && (
            <button
              type="button"
              onClick={() => submit(true)}
              disabled={approveMutation.isPending}
              className="flex items-center gap-1.5 rounded-xl bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-emerald-700 disabled:opacity-50"
            >
              {approveMutation.isPending ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Check className="h-3.5 w-3.5" />
              )}
              Approve spec
            </button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
