import type { NewQuoteForm } from "./types";

export const NEW_QUOTE_DEFAULTS: NewQuoteForm = {
  packageType: "",
  quoteTitle: "",
  quoteLink: "",
  jsonPayload: "",
  travelDate: "",
  passengersAdults: 2,
  passengersChildren: 0,
  passengersInfants: 0,
  childAges: [],
  country: "",
  destination: "",
  resort: "",
  accommodation: "",
  checkInDate: "",
  checkInTime: "",
  nights: 7,
  boardBasis: "",
  roomType: "",
  transferType: "",
  preBookedSeats: "",
  flightMeals: "",
  leadSource: "",
  outboundDepartAirport: "",
  outboundDepartDate: "",
  outboundDepartTime: "",
  outboundArriveAirport: "",
  outboundArriveDate: "",
  outboundArriveTime: "",
  inboundDepartAirport: "",
  inboundDepartDate: "",
  inboundDepartTime: "",
  inboundArriveAirport: "",
  inboundArriveDate: "",
  inboundArriveTime: "",
  tourOperator: "",
  sales: 0,
  price: 0,
  commission: 0,
  discount: 0,
  serviceCharge: 0,
  pricePerPerson: 0,
  returnDate: "",
  haysReference: "",
  tourReference: "",
  cruiseTitle: "",
  cruiseLine: "",
  shipName: "",
  cruiseDate: "",
  cabinType: "",
  embarkation: "",
  debarkation: "",
  cruiseExtras: "",
  cruiseOnly: false,
  lodgeCode: "",
  parkName: "",
  pets: false,
};

export const EDIT_CLIENT_DEFAULTS = {
  title: "",
  firstName: "",
  surename: "",
  phoneNumber: "",
  email: "",
  DOB: "",
  houseNumber: "",
  street: "",
  city: "",
  country: "",
  post_code: "",
  badge: "",
};
