// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tickets-layouts/DenseTable.tsx": () => import("../components/mockups/tickets-layouts/DenseTable.tsx"),
  "./components/mockups/tickets-layouts/KanbanBoard.tsx": () => import("../components/mockups/tickets-layouts/KanbanBoard.tsx"),
  "./components/mockups/tickets-layouts/SplitPanel.tsx": () => import("../components/mockups/tickets-layouts/SplitPanel.tsx")
};
