import { taskRepository, entityLink, type TaskWithClient } from "./task.repository";
import { notificationRepository } from "../notification/notification.repository";
import { AppError } from "../../utils/error-handler";
import { tasks } from "@shared/schema";
import type { Scope } from "../../utils/scope";

type TaskNew = typeof tasks.$inferSelect;
// id is generated by the repository (randomUUID), so callers never supply it.
type InsertTaskNew = Omit<typeof tasks.$inferInsert, "id">;

// A self-assigned task is silent EXCEPT when it's attached to one of these
// entities — the user's own words were "it should create a task notification
// if there's a task on the enquiry or quote", so a task standing alone (or on
// a booking/client) stays silent when you assign it to yourself.
const SELF_ASSIGN_NOTIFY_ENTITY_TYPES = new Set(["enquiry", "quote"]);

/**
 * Fires the "you were assigned a task" notification. Best-effort: a failure
 * here must never fail the create/update the caller is waiting on.
 *
 * - Unassigned (`userId` null) never notifies.
 * - Assigning to yourself never notifies, unless the task hangs off an
 *   enquiry or quote — those self-assigned tasks still notify.
 */
async function notifyTaskAssignment(task: TaskNew, actingUserId: string | null): Promise<void> {
  if (!task.userId) return;

  const isSelfAssign = actingUserId != null && task.userId === actingUserId;
  const isEntityException = task.entityType != null && SELF_ASSIGN_NOTIFY_ENTITY_TYPES.has(task.entityType);
  if (isSelfAssign && !isEntityException) return;

  try {
    await notificationRepository.create({
      userId: task.userId,
      type: "task_assigned",
      title: "Task assigned to you",
      message: `You were assigned the task "${task.title ?? "Untitled"}"`,
      link: entityLink(task.entityType ?? "", task.entityId ?? ""),
      read: false,
    });
  } catch (err) {
    console.warn(`[tasks] assignment notification failed for task ${task.id}:`, err);
  }
}

export const taskService = {
  async listAll(userId?: string, scope?: Scope): Promise<TaskWithClient[]> {
    return await taskRepository.findAll(userId, scope);
  },

  async listAllWithClientTasks(userId?: string, scope?: Scope): Promise<TaskWithClient[]> {
    return await taskRepository.findAllWithClientTasks(userId, scope);
  },

  async listByEntity(entityType: string, entityId: string, scope?: Scope): Promise<TaskNew[]> {
    return await taskRepository.findByEntity(entityType, entityId, scope);
  },

  async listByUser(
    userId: string,
    scope?: Scope,
    filters?: { dueFrom?: Date; dueTo?: Date; incomplete?: boolean },
  ): Promise<TaskWithClient[]> {
    return await taskRepository.findAllWithClientTasks(userId, scope, filters);
  },

  async create(data: InsertTaskNew, scope?: Scope): Promise<TaskNew> {
    const result = await taskRepository.create(data, scope);
    await notifyTaskAssignment(result, scope?.userId ?? null);
    return result;
  },

  async update(id: string, data: Partial<InsertTaskNew>, scope?: Scope): Promise<TaskNew> {
    // Keep completedAt in step with the completed flag so it matches what the
    // toggle endpoint stamps — the controller never accepts completedAt directly.
    const patch: Partial<InsertTaskNew> =
      data.completed === undefined
        ? data
        : { ...data, completedAt: data.completed ? new Date() : null };

    // Only needed when the assignee is actually part of this patch — the
    // edit form resends the current assignee on every save, so without this
    // comparison an unrelated field edit (or a resave that echoes the same
    // assignee back) would re-notify.
    const previous = data.userId !== undefined ? await taskRepository.findById(id, scope) : undefined;

    const result = await taskRepository.update(id, patch, scope);
    if (!result) throw new AppError("Task not found", 404);

    if (data.userId !== undefined && result.userId !== previous?.userId) {
      await notifyTaskAssignment(result, scope?.userId ?? null);
    }

    return result;
  },

  async toggleComplete(id: string, scope?: Scope): Promise<TaskNew> {
    const result = await taskRepository.toggleComplete(id, scope);
    if (!result) throw new AppError("Task not found", 404);
    return result;
  },

  async remove(id: string, scope?: Scope): Promise<void> {
    const removed = await taskRepository.remove(id, scope);
    if (!removed) throw new AppError("Task not found", 404);
  },

  async reassignByEntity(entityType: string, entityId: string, newUserId: string): Promise<void> {
    await taskRepository.reassignByEntity(entityType, entityId, newUserId);
  },

  async completeByEntity(entityType: string, entityId: string): Promise<void> {
    await taskRepository.completeByEntity(entityType, entityId);
  },
};
