/**
 * Allocate the canonical tour-operator catalog to organization(s).
 *
 * Source of truth: scripts/seed-data/tour-operator-commission.ts (150 operators,
 * each with a commission_percentage). Because tour_operator.org_id is a single
 * column and the settings layer scopes strictly by org_id (no shared/global
 * operators), every org needs its OWN copy of the catalog. Each row is inserted
 * with a FRESH id (the seed's canonical ids already belong to other orgs, so
 * reusing them would collide on the primary key).
 *
 * Idempotent: within a target org, an operator whose name already exists is
 * skipped — safe to re-run, never duplicates.
 *
 * Usage:
 *   npm run db:seed-org-tour-operators                 # default org (below)
 *   npm run db:seed-org-tour-operators -- <org-uuid>   # a specific org
 *   npm run db:seed-org-tour-operators -- all          # every organization
 */
import { db } from "../server/config/database";
import { tour_operator, organization } from "../shared/schema";
import { eq } from "drizzle-orm";
import { tourOperatorCommissionSeed } from "./seed-data/tour-operator-commission";

// The org requested for this allocation. Override with a CLI arg or "all".
const DEFAULT_ORG_ID = "05348914-c08c-4c37-8733-3ad91179da38";

const norm = (s: string | null | undefined) => (s || "").trim().toLowerCase();

async function seedOrg(orgId: string, orgName: string): Promise<{ inserted: number; skipped: number }> {
  // Existing operator names in this org — the idempotency key.
  const existing = await db
    .select({ name: tour_operator.name })
    .from(tour_operator)
    .where(eq(tour_operator.org_id, orgId));
  const seen = new Set(existing.map((r) => norm(r.name)));

  const toInsert: { name: string; commission_percentage: string; org_id: string }[] = [];
  for (const op of tourOperatorCommissionSeed) {
    const key = norm(op.name);
    if (!key || seen.has(key)) continue; // skip blanks, already-present, and in-seed dupes
    seen.add(key);
    toInsert.push({ name: op.name!, commission_percentage: op.commission_percentage, org_id: orgId });
  }

  if (toInsert.length > 0) {
    // Fresh ids are generated by the table default (gen_random_uuid()).
    await db.insert(tour_operator).values(toInsert);
  }

  const skipped = tourOperatorCommissionSeed.length - toInsert.length;
  console.log(`  ${orgName} (${orgId}): inserted ${toInsert.length}, skipped ${skipped}`);
  return { inserted: toInsert.length, skipped };
}

async function main() {
  const arg = process.argv[2]?.trim();

  let targets: { id: string; name: string | null }[];
  if (arg === "all") {
    targets = await db.select({ id: organization.id, name: organization.name }).from(organization);
    console.log(`Allocating tour operators to ALL ${targets.length} organization(s)...`);
  } else {
    const orgId = arg || DEFAULT_ORG_ID;
    const [org] = await db
      .select({ id: organization.id, name: organization.name })
      .from(organization)
      .where(eq(organization.id, orgId))
      .limit(1);
    if (!org) {
      console.error(`Organization not found: ${orgId}`);
      process.exit(1);
    }
    targets = [org];
    console.log(`Allocating ${tourOperatorCommissionSeed.length} tour operators to "${org.name}" (${org.id})...`);
  }

  let totalInserted = 0;
  let totalSkipped = 0;
  for (const org of targets) {
    const { inserted, skipped } = await seedOrg(org.id, org.name ?? "(unnamed)");
    totalInserted += inserted;
    totalSkipped += skipped;
  }

  console.log("\nDone.");
  console.log(`  total inserted: ${totalInserted}`);
  console.log(`  total skipped (already present): ${totalSkipped}`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
