import { Router } from 'express';
import { isAuthenticated } from '../middlewares/auth';
import { orgBranchScope } from '../middlewares/org-branch-scope';

import onboardingRoutes from '../modules/onboarding/onboarding.routes';
import userRoutes from '../modules/user/user.routes';
import clientRoutes from '../modules/client/client.routes';
import clientFileRoutes from '../modules/client/client-file.routes';
import transactionRoutes from '../modules/transaction/transaction.routes';
import quoteRoutes from '../modules/quote/quote.routes';
import bookingRoutes from '../modules/booking/booking.routes';
import enquiryRoutes from '../modules/enquiry/enquiry.routes';
import noteRoutes from '../modules/note/note.routes';
import tourOperatorRoutes from '../modules/tour-operator/tour-operator.routes';
import airportRoutes from '../modules/airport/airport.routes';
import ticketRoutes from '../modules/ticket/ticket.routes';
import ticketAttachmentRoutes from '../modules/ticket/ticket-attachment.routes';
import ticketReplyRoutes from '../modules/ticket/ticket-reply.routes';
import notificationRoutes from '../modules/notification/notification.routes';
import dashboardRoutes from '../modules/dashboard/dashboard.routes';
import favoriteRoutes from '../modules/favorite/favorite.routes';
import taskRoutes from '../modules/task/task.routes';
import tagRoutes from '../modules/tag/tag.routes';
import chatRoutes from '../modules/chat/chat.routes';
import socialPostRoutes from '../modules/social-post/social-post.routes';
import emailRoutes from '../modules/email/email.routes';
import facebookRoutes from '../modules/facebook/facebook.routes';
import opportunitiesRoutes from '../modules/opportunities/opportunities.routes';
import revenueRoutes from '../modules/revenue/revenue.routes';
import targetsRoutes from '../modules/targets/targets.routes';
import searchRoutes from '../modules/search/search.routes';
import referralRoutes from '../modules/referral/referral.routes';
import referralPayoutRoutes from '../modules/referral/referral-payout.routes';
import referralWithdrawalRoutes from '../modules/referral/referral-withdrawal.routes';
import walletRoutes from '../modules/wallet/wallet.routes';
import smsRoutes from '../modules/sms/sms.routes';
import neonClientRoutes from '../modules/neon-client/neon-client.routes';
import aiAskRoutes from '../modules/ai-ask/ai-ask.routes';
import destinationGuruRoutes from '../modules/destination-guru/destination-guru.routes';
import jsonMapperRoutes from '../modules/json-mapper/json-mapper.routes';
import announcementRoutes from '../modules/announcement/announcement.routes';
import auditRoutes from '../modules/audit/audit.routes';
import feedbackRoutes from '../modules/feedback/feedback.routes';
import hrRoutes from '../modules/hr/hr.routes';
import hubPostRoutes from '../modules/hub-post/hub-post.routes';
import adminImportRoutes from '../modules/admin-import/admin-import.routes';
import quoteShareRoutes from '../modules/quote-share/quote-share.routes';
import portalRoutes from '../modules/portal/portal.routes';
import branchRoutes from '../modules/branch/branch.routes';
import inviteRoutes from '../modules/invite/invite.routes';
import platformAdminRoutes from '../modules/platform-admin/platform-admin.routes';
import lookupRoutes from '../lookup/lookup.routes';
import settingsRoutes from '../settings';

const router = Router();
const auth = [isAuthenticated, orgBranchScope] as const;

router.use('/onboarding',         onboardingRoutes);
router.use('/users',              ...auth, userRoutes);
router.use('/branches',           ...auth, branchRoutes);
router.use('/invites',            ...auth, inviteRoutes);
router.use('/clients',            ...auth, clientRoutes);
router.use('/client-files',       ...auth, clientFileRoutes);
router.use('/transactions',       ...auth, transactionRoutes);
router.use('/quotes',             ...auth, quoteRoutes);
router.use('/bookings',           ...auth, bookingRoutes);
router.use('/enquiries',          ...auth, enquiryRoutes);
router.use('/notes',              ...auth, noteRoutes);
router.use('/tour-operators',     ...auth, tourOperatorRoutes);
router.use('/airports',           isAuthenticated, airportRoutes);
router.use('/tickets',            ...auth, ticketRoutes);
router.use('/attachments',        isAuthenticated, ticketAttachmentRoutes);
router.use('/replies',            isAuthenticated, ticketReplyRoutes);
router.use('/notifications',      isAuthenticated, notificationRoutes);
router.use('/dashboard',          ...auth, dashboardRoutes);
router.use('/favorites',          isAuthenticated, favoriteRoutes);
router.use('/tasks',              ...auth, taskRoutes);
router.use('/tags',               isAuthenticated, tagRoutes);
router.use('/chat',               isAuthenticated, chatRoutes);
router.use('/social-posts',       isAuthenticated, socialPostRoutes);
router.use('/emails',             isAuthenticated, emailRoutes);
router.use('/facebook',           isAuthenticated, facebookRoutes);
router.use('/opportunities',      ...auth, opportunitiesRoutes);
router.use('/revenue',            ...auth, revenueRoutes);
router.use('/targets',            ...auth, targetsRoutes);
router.use('/search',             isAuthenticated, searchRoutes);
router.use('/referrals',          isAuthenticated, referralRoutes);
router.use('/referral-payouts',   isAuthenticated, referralPayoutRoutes);
router.use('/referral-withdrawals', isAuthenticated, referralWithdrawalRoutes);
router.use('/wallet',             isAuthenticated, walletRoutes);
router.use('/sms',                isAuthenticated, smsRoutes);
router.use('/neon-clients',       ...auth, neonClientRoutes);
router.use('/ai',                 isAuthenticated, aiAskRoutes);
router.use('/destination-guru',   isAuthenticated, destinationGuruRoutes);
router.use('/json-mapper',        isAuthenticated, jsonMapperRoutes);
router.use('/announcements',      isAuthenticated, announcementRoutes);
router.use('/audit',              isAuthenticated, auditRoutes);
router.use('/feedback',           isAuthenticated, feedbackRoutes);
router.use('/hr',                 isAuthenticated, hrRoutes);
router.use('/hub-posts',          isAuthenticated, hubPostRoutes);
router.use('/admin',              isAuthenticated, adminImportRoutes);
router.use('/quote-share',        isAuthenticated, quoteShareRoutes);
router.use('/portal',             portalRoutes);
router.use('/platform-admin',     isAuthenticated, platformAdminRoutes);
router.use('/lookup',             lookupRoutes);
router.use('/settings',           isAuthenticated, settingsRoutes);

export default router;
