import { Router } from 'express';
import { isAuthenticated, requirePlatformAdmin } from '../middlewares/auth';
import { orgBranchScope } from '../middlewares/org-branch-scope';
import { errorHandler } from '../middlewares/error.middleware';

import onboardingRoutes from '../modules/onboarding/onboarding.routes';
import userRoutes from '../modules/user/user.routes';
import clientRoutes from '../modules/client/client.routes';
import clientFileRoutes from '../modules/client/client-file.routes';
import transactionRoutes from '../modules/transaction/transaction.routes';
import quoteRoutes from '../modules/quote/quote.routes';
import bookingRoutes from '../modules/booking/booking.routes';
import bookingUpsellRoutes from '../modules/booking/booking-upsell.routes';
import enquiryRoutes from '../modules/enquiry/enquiry.routes';
import noteRoutes from '../modules/note/note.routes';
import tourOperatorRoutes from '../modules/tour-operator/tour-operator.routes';
import airportRoutes from '../modules/airport/airport.routes';
import ticketRoutes from '../modules/ticket/ticket.routes';
import ticketAttachmentRoutes from '../modules/ticket/ticket-attachment.routes';
import ticketReplyRoutes from '../modules/ticket/ticket-reply.routes';
import notificationRoutes from '../modules/notification/notification.routes';
import dashboardRoutes from '../modules/dashboard/dashboard.routes';
import branchOverviewRoutes from '../modules/branch-overview/branch-overview.routes';
import organizationOverviewRoutes from '../modules/organization-overview/organization-overview.routes';
import reportsRoutes from '../modules/reports/reports.routes';
import favoriteRoutes from '../modules/favorite/favorite.routes';
import taskRoutes from '../modules/task/task.routes';
import tagRoutes from '../modules/tag/tag.routes';
import chatRoutes from '../modules/chat/chat.routes';
import conversationsRoutes from '../modules/conversations/conversations.routes';
import messagesRoutes from '../modules/messages/messages.routes';
import conversationIntegrationRoutes from '../modules/conversation-integration/conversation-integration.routes';
import { sendSevenContext } from '../modules/conversation-integration/conversation-integration.middleware';
import channelsRoutes from '../modules/channels/channels.routes';
import contactLinkRoutes from '../modules/contact-link/contact-link.routes';
import sendsevenWebhookRoutes from '../modules/sendseven-webhook/sendseven-webhook.routes';
import botConfigRoutes from '../modules/bot-config/bot-config.routes';
import knowledgeBaseRoutes from '../modules/knowledge-base/knowledge-base.routes';
import inboxesRoutes from '../modules/inboxes/inboxes.routes';
import socialPostRoutes from '../modules/social-post/social-post.routes';
import emailRoutes from '../modules/email/email.routes';
import facebookRoutes from '../modules/facebook/facebook.routes';
import opportunitiesRoutes from '../modules/opportunities/opportunities.routes';
import revenueRoutes from '../modules/revenue/revenue.routes';
import targetsRoutes from '../modules/targets/targets.routes';
import searchRoutes from '../modules/search/search.routes';
import referralRoutes from '../modules/referral/referral.routes';
import referralPayoutRoutes from '../modules/referral/referral-payout.routes';
import referralWithdrawalRoutes from '../modules/referral/referral-withdrawal.routes';
import walletRoutes from '../modules/wallet/wallet.routes';
import smsRoutes from '../modules/sms/sms.routes';
import neonClientRoutes from '../modules/neon-client/neon-client.routes';
import aiAskRoutes from '../modules/ai-ask/ai-ask.routes';
import aiEnquiryRoutes from '../modules/ai-enquiry/ai-enquiry.routes';
import destinationGuruRoutes from '../modules/destination-guru/destination-guru.routes';
import jsonMapperRoutes from '../modules/json-mapper/json-mapper.routes';
import easyjetRoutes from '../modules/easyjet/easyjet.routes';
import scraperRoutes from '../modules/scraper/scraper.routes';
import announcementRoutes from '../modules/announcement/announcement.routes';
import auditRoutes from '../modules/audit/audit.routes';
import feedbackRoutes from '../modules/feedback/feedback.routes';
import hrRoutes from '../modules/hr/hr.routes';
import hubPostRoutes from '../modules/hub-post/hub-post.routes';
import adminImportRoutes from '../modules/admin-import/admin-import.routes';
import quoteShareRoutes from '../modules/quote-share/quote-share.routes';
import portalRoutes from '../modules/portal/portal.routes';
import branchRoutes from '../modules/branch/branch.routes';
import organizationRoutes from '../modules/organization/organization.routes';
import planRoutes from '../modules/plan/plan.routes';
import inviteRoutes from '../modules/invite/invite.routes';
import platformAdminRoutes from '../modules/platform-admin/platform-admin.routes';
import userOrgRolesRoutes from '../modules/user-org-roles/user-org-roles.routes';
import lookupRoutes from '../lookup/lookup.routes';
import settingsRoutes from '../settings';
import fileRoutes from '../modules/files/file.routes';
import trainingRoutes from '../modules/training/training.routes';
import internalChatRoutes from '../modules/internal-chat/internal-chat.routes';
import realtimeRoutes from '../realtime/realtime.routes';
import usageRoutes from '../modules/usage/usage.routes';

const router = Router();
const auth = [isAuthenticated, orgBranchScope] as const;

router.use('/files',              fileRoutes);
router.use('/onboarding',         onboardingRoutes);
// Public: SendSeven webhook receiver — signature-verified, no session auth.
router.use('/sendseven-webhook',  sendsevenWebhookRoutes);
router.use('/users',              ...auth, userRoutes);
router.use('/branches',           ...auth, branchRoutes);
router.use('/organizations',      organizationRoutes);
router.use('/plans',              ...auth, planRoutes);
router.use('/invites',            inviteRoutes);
router.use('/clients',            ...auth, clientRoutes);
router.use('/client-files',       ...auth, clientFileRoutes);
router.use('/transactions',       ...auth, transactionRoutes);
router.use('/quotes',             ...auth, quoteRoutes);
router.use('/bookings',           ...auth, bookingRoutes);
router.use('/upsells',            ...auth, bookingUpsellRoutes);
router.use('/enquiries',          ...auth, enquiryRoutes);
router.use('/notes',              ...auth, noteRoutes);
router.use('/tour-operators',     ...auth, tourOperatorRoutes);
router.use('/airports',           isAuthenticated, airportRoutes);
router.use('/tickets',            ...auth, ticketRoutes);
router.use('/attachments',        ...auth, ticketAttachmentRoutes);
router.use('/replies',            ...auth, ticketReplyRoutes);
router.use('/notifications',      isAuthenticated, notificationRoutes);
router.use('/dashboard',          ...auth, dashboardRoutes);
router.use('/branch-overview',    ...auth, branchOverviewRoutes);
router.use('/organization-overview', ...auth, organizationOverviewRoutes);
router.use('/reports',            ...auth, reportsRoutes);
router.use('/favorites',          isAuthenticated, favoriteRoutes);
router.use('/tasks',              ...auth, taskRoutes);
router.use('/tags',               isAuthenticated, tagRoutes);
router.use('/chat',               isAuthenticated, chatRoutes);
router.use('/conversation-integration', isAuthenticated, requirePlatformAdmin, conversationIntegrationRoutes);
router.use('/conversations',      ...auth, sendSevenContext, conversationsRoutes);
router.use('/messages',           ...auth, sendSevenContext, messagesRoutes);
router.use('/channels',           ...auth, sendSevenContext, channelsRoutes);
router.use('/contact-links',      ...auth, contactLinkRoutes);
router.use('/bot-config',         ...auth, botConfigRoutes);
router.use('/knowledge-base',     ...auth, knowledgeBaseRoutes);
router.use('/inboxes',            ...auth, sendSevenContext, inboxesRoutes);
router.use('/social-posts',       ...auth, socialPostRoutes);
router.use('/emails',             isAuthenticated, emailRoutes);
router.use('/facebook',           isAuthenticated, facebookRoutes);
router.use('/opportunities',      ...auth, opportunitiesRoutes);
router.use('/revenue',            ...auth, revenueRoutes);
router.use('/targets',            ...auth, targetsRoutes);
router.use('/search',             ...auth, searchRoutes);
router.use('/referrals',          ...auth, referralRoutes);
router.use('/referral-payouts',   ...auth, referralPayoutRoutes);
router.use('/referral-withdrawals', ...auth, referralWithdrawalRoutes);
router.use('/wallet',             ...auth, walletRoutes);
router.use('/sms',                ...auth, smsRoutes);
router.use('/neon-clients',       ...auth, neonClientRoutes);
router.use('/ai',                 ...auth, aiAskRoutes);
router.use('/ai-enquiry',         ...auth, aiEnquiryRoutes);
router.use('/destination-guru',   ...auth, destinationGuruRoutes);
router.use('/json-mapper',        isAuthenticated, jsonMapperRoutes);
router.use('/easyjet',            ...auth, easyjetRoutes);
router.use('/scrapers',           ...auth, scraperRoutes);
router.use('/announcements',      ...auth, announcementRoutes);
router.use('/audit',              ...auth, auditRoutes);
router.use('/feedback',           ...auth, feedbackRoutes);
router.use('/hr',                 ...auth, hrRoutes);
router.use('/hub-posts',          ...auth, hubPostRoutes);
router.use('/admin',              ...auth, adminImportRoutes);
router.use('/quote-share',        isAuthenticated, quoteShareRoutes);
router.use('/portal',             portalRoutes);
router.use('/platform-admin',     isAuthenticated, platformAdminRoutes);
router.use('/user-org-roles',     ...auth, userOrgRolesRoutes);
router.use('/lookup',             lookupRoutes);
router.use('/settings',           ...auth, settingsRoutes);
router.use('/training',           ...auth, trainingRoutes);
router.use('/internal-chat',      ...auth, internalChatRoutes);
router.use('/realtime',           ...auth, realtimeRoutes);
router.use('/usage',              ...auth, usageRoutes);

// v2 error handler — must be LAST so it catches errors from every v2 route above.
// Without this, v2 errors bubble to the global v1 errorHandler, whose `instanceof
// AppError` check fails against the v2 AppError class and turns every operational
// error (404/400/409) into a generic 500.
router.use(errorHandler);

export default router;
